events {}

http {
    upstream ml_service {
        # при ошибках новой версии весь трафик возвращается
        server stable:8000 weight=1;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ml_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
