events {}

http {
    upstream ml_service {
        # стабильная версия основную часть трафика
        server stable:8000 weight=9;

        # новая canary-версия малую долю трафика
        server canary:8000 weight=1;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ml_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
